name: Build Android APK

on:
  # Trigger the workflow on push or pull request to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Run flutter pub get to install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build APK (for Android)
      - name: Build APK
        run: flutter build apk --no-shrink

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk
